wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 64
latent_dim:
  desc: null
  value: 20
layer_loss_weight:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700485036.034623
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
